package pennon.handinhand.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;

public class Banner implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.catid
     *
     * @mbg.generated
     */
    private Short catid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.typeid
     *
     * @mbg.generated
     */
    private Short typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.style
     *
     * @mbg.generated
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.thumb
     *
     * @mbg.generated
     */
    private String thumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.posids
     *
     * @mbg.generated
     */
    private Byte posids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.listorder
     *
     * @mbg.generated
     */
    private Byte listorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.sysadd
     *
     * @mbg.generated
     */
    private Byte sysadd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.islink
     *
     * @mbg.generated
     */
    private Byte islink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.inputtime
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Integer inputtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v9_news_banner.updatetime
     *
     * @mbg.generated
     */
    @JsonIgnore
    private Integer updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.id
     *
     * @return the value of v9_news_banner.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.id
     *
     * @param id the value for v9_news_banner.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.catid
     *
     * @return the value of v9_news_banner.catid
     *
     * @mbg.generated
     */
    public Short getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withCatid(Short catid) {
        this.setCatid(catid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.catid
     *
     * @param catid the value for v9_news_banner.catid
     *
     * @mbg.generated
     */
    public void setCatid(Short catid) {
        this.catid = catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.typeid
     *
     * @return the value of v9_news_banner.typeid
     *
     * @mbg.generated
     */
    public Short getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withTypeid(Short typeid) {
        this.setTypeid(typeid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.typeid
     *
     * @param typeid the value for v9_news_banner.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Short typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.title
     *
     * @return the value of v9_news_banner.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.title
     *
     * @param title the value for v9_news_banner.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.style
     *
     * @return the value of v9_news_banner.style
     *
     * @mbg.generated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withStyle(String style) {
        this.setStyle(style);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.style
     *
     * @param style the value for v9_news_banner.style
     *
     * @mbg.generated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.thumb
     *
     * @return the value of v9_news_banner.thumb
     *
     * @mbg.generated
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withThumb(String thumb) {
        this.setThumb(thumb);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.thumb
     *
     * @param thumb the value for v9_news_banner.thumb
     *
     * @mbg.generated
     */
    public void setThumb(String thumb) {
        this.thumb = thumb == null ? null : thumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.keywords
     *
     * @return the value of v9_news_banner.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withKeywords(String keywords) {
        this.setKeywords(keywords);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.keywords
     *
     * @param keywords the value for v9_news_banner.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.description
     *
     * @return the value of v9_news_banner.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.description
     *
     * @param description the value for v9_news_banner.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.posids
     *
     * @return the value of v9_news_banner.posids
     *
     * @mbg.generated
     */
    public Byte getPosids() {
        return posids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withPosids(Byte posids) {
        this.setPosids(posids);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.posids
     *
     * @param posids the value for v9_news_banner.posids
     *
     * @mbg.generated
     */
    public void setPosids(Byte posids) {
        this.posids = posids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.url
     *
     * @return the value of v9_news_banner.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.url
     *
     * @param url the value for v9_news_banner.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.listorder
     *
     * @return the value of v9_news_banner.listorder
     *
     * @mbg.generated
     */
    public Byte getListorder() {
        return listorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withListorder(Byte listorder) {
        this.setListorder(listorder);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.listorder
     *
     * @param listorder the value for v9_news_banner.listorder
     *
     * @mbg.generated
     */
    public void setListorder(Byte listorder) {
        this.listorder = listorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.status
     *
     * @return the value of v9_news_banner.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withStatus(Byte status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.status
     *
     * @param status the value for v9_news_banner.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.sysadd
     *
     * @return the value of v9_news_banner.sysadd
     *
     * @mbg.generated
     */
    public Byte getSysadd() {
        return sysadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withSysadd(Byte sysadd) {
        this.setSysadd(sysadd);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.sysadd
     *
     * @param sysadd the value for v9_news_banner.sysadd
     *
     * @mbg.generated
     */
    public void setSysadd(Byte sysadd) {
        this.sysadd = sysadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.islink
     *
     * @return the value of v9_news_banner.islink
     *
     * @mbg.generated
     */
    public Byte getIslink() {
        return islink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withIslink(Byte islink) {
        this.setIslink(islink);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.islink
     *
     * @param islink the value for v9_news_banner.islink
     *
     * @mbg.generated
     */
    public void setIslink(Byte islink) {
        this.islink = islink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.username
     *
     * @return the value of v9_news_banner.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withUsername(String username) {
        this.setUsername(username);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.username
     *
     * @param username the value for v9_news_banner.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.inputtime
     *
     * @return the value of v9_news_banner.inputtime
     *
     * @mbg.generated
     */
    public Integer getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withInputtime(Integer inputtime) {
        this.setInputtime(inputtime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.inputtime
     *
     * @param inputtime the value for v9_news_banner.inputtime
     *
     * @mbg.generated
     */
    public void setInputtime(Integer inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v9_news_banner.updatetime
     *
     * @return the value of v9_news_banner.updatetime
     *
     * @mbg.generated
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    public Banner withUpdatetime(Integer updatetime) {
        this.setUpdatetime(updatetime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v9_news_banner.updatetime
     *
     * @param updatetime the value for v9_news_banner.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v9_news_banner
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", catid=").append(catid);
        sb.append(", typeid=").append(typeid);
        sb.append(", title=").append(title);
        sb.append(", style=").append(style);
        sb.append(", thumb=").append(thumb);
        sb.append(", keywords=").append(keywords);
        sb.append(", description=").append(description);
        sb.append(", posids=").append(posids);
        sb.append(", url=").append(url);
        sb.append(", listorder=").append(listorder);
        sb.append(", status=").append(status);
        sb.append(", sysadd=").append(sysadd);
        sb.append(", islink=").append(islink);
        sb.append(", username=").append(username);
        sb.append(", inputtime=").append(inputtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}