package pennon.handinhand.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
import pennon.handinhand.entity.Preference;
import pennon.handinhand.entity.PreferenceExample;

@Repository
public interface PreferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    long countByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int deleteByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int insert(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int insertSelective(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    List<Preference> selectByExampleWithRowbounds(PreferenceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    List<Preference> selectByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    Preference selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Preference record, @Param("example") PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Preference record, @Param("example") PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Preference record);
}