package pennon.handinhand.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
import pennon.handinhand.entity.PreferenceLog;
import pennon.handinhand.entity.PreferenceLogExample;

@Repository
public interface PreferenceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    long countByExample(PreferenceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int deleteByExample(PreferenceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int insert(PreferenceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int insertSelective(PreferenceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    List<PreferenceLog> selectByExampleWithRowbounds(PreferenceLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    List<PreferenceLog> selectByExample(PreferenceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    PreferenceLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PreferenceLog record, @Param("example") PreferenceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PreferenceLog record, @Param("example") PreferenceLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PreferenceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PreferenceLog record);
}